const portfolioData = [
    {
        id: 'dev',
        title: '데블록 자사 홈페이지 리뉴얼',
        type: 'work',
        section: ['웹 페이지'],
        whatTodo: ['기존 홈페이지 리뉴얼'],
        thumbImage: true,
        detailImage: true,
        link: 'https://devlock.co.kr/',
        percentage: '90%',
        tech: ['React.js', 'scss'],
    },
    {
        id: 'medicoson',
        title: '메디코슨',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: false,
        detailImage: true,
        percentage: '90%',
        tech: ['Jquery', 'css'],
    },
    {
        id: 'wdd',
        title: '원격 비대면진료 서비스 후다닥케어',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: false,
        detailImage: true,
        percentage: '80%',
        tech: ['Vue.js', 'Vuex'],
    },
    {
        id: 'msm',
        title: '엄마의지도',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발', '유지/보수'],
        thumbImage: true,
        detailImage: true,
        percentage: '30%',
        tech: ['Jquery', 'css'],
    },
    {
        id: 'mag',
        title: '콘텐츠 결합형 AI 마음성장 플랫폼 마인드그라프',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
        tech: ['Jquery', 'css'],
    },
    {
        id: 'wap',
        title: '와인 소셜 커뮤니티 플랫폼 와프너',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
        tech: ['Jquery', 'css'],
    },
    {
        id: 'bac',
        title: 'BAC 블랙야크 알파인 클럽',
        type: 'work',
        section: ['관리자 페이지 개발'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
        tech: ['Jquery', 'css'],
    },
    {
        id: 'todolist',
        title: 'To Do List',
        type: 'side',
        section: ['웹 페이지'],
        whatTodo: 'localStorage 사용해서 CRUD 구현, 다크모드',
        thumbImage: true,
        detailImage: false,
        link: 'https://rnjswltn1020.github.io/todoListReact/',
        percentage: '100%',
        tech: ['React.js', 'styled-components'],
    },
    {
        id: 'ordinaryCloset',
        title: 'Ordinary closet',
        type: 'side',
        section: ['웹 페이지'],
        whatTodo: 'Firebase 기반 realtime database, auth Login 기능구현',
        thumbImage: true,
        detailImage: false,
        link: 'https://ordinarycloset.netlify.app/',
        percentage: '100%',
        tech: ['React.js', 'styled-components'],
    },
];
export default portfolioData;
