const portfolioData = [
    {
        id: 'onnuri',
        title: '온누리 약국',
        group: ['SERVICE'],
        section: ['Admin Page'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'dev',
        title: '데블록 자사 홈페이지 리뉴얼',
        group: ['SERVICE'],
        section: ['Web page'],
        whatTodo: ['기존 홈페이지 리뉴얼'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'medicoson',
        title: '메디코슨',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'wdd',
        title: '원격 비대면진료 서비스 후다닥케어',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'msm',
        title: '엄마의지도',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: ['어드민페이지 개발','유지/보수'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'mag',
        title: '콘텐츠 결합형 AI 마음성장 플랫폼 마인드그라프',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'wap',
        title: '와인 소셜 커뮤니티 플랫폼 와프너',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'bac',
        title: 'BAC 블랙야크 알파인 클럽',
        group: ['SERVICE'],
        section: ['Admin page'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
];
export default portfolioData;
