const portfolioData = [
    {
        id: 'dev',
        title: '데블록 자사 홈페이지 리뉴얼',
        type: 'work',
        section: ['웹 페이지'],
        whatTodo: ['기존 홈페이지 리뉴얼'],
        thumbImage: true,
        detailImage: true,
        link: 'https://devlock.co.kr/',
    },
    {
        id: 'medicoson',
        title: '메디코슨',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: false,
        detailImage: true,
    },
    {
        id: 'wdd',
        title: '원격 비대면진료 서비스 후다닥케어',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발'],
        thumbImage: false,
        detailImage: true,
    },
    {
        id: 'msm',
        title: '엄마의지도',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: ['어드민페이지 개발', '유지/보수'],
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'mag',
        title: '콘텐츠 결합형 AI 마음성장 플랫폼 마인드그라프',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'wap',
        title: '와인 소셜 커뮤니티 플랫폼 와프너',
        type: 'work',
        section: ['관리자 페이지'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'bac',
        title: 'BAC 블랙야크 알파인 클럽',
        type: 'work',
        section: ['Admin page'],
        whatTodo: '유지/보수',
        thumbImage: true,
        detailImage: true,
    },
    {
        id: 'todolist',
        title: 'To Do List',
        type: 'side',
        section: ['웹 페이지'],
        whatTodo: '웹개발',
        thumbImage: true,
        detailImage: false,
        link: 'https://rnjswltn1020.github.io/todoListReact/',
    },
    {
        id: 'ordinaryCloset',
        title: 'Ordinary closet',
        type: 'side',
        section: ['웹 페이지'],
        whatTodo: '웹개발',
        thumbImage: true,
        detailImage: false,
        link: 'https://ordinarycloset.netlify.app/',
    },
];
export default portfolioData;
